name: chat_app_class
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_messaging: ^14.2.1
  http: ^0.13.5
  googleapis_auth: ^1.3.1
  fluttertoast: ^8.1.2
  chat_bubbles: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
   - images/
