// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgXN230DZoK_YZnDkfpym8QoowFpDZyCc',
    appId: '1:590391716016:web:baba26b060e15cec51f375',
    messagingSenderId: '590391716016',
    projectId: 'new-chat-75fdb',
    authDomain: 'new-chat-75fdb.firebaseapp.com',
    storageBucket: 'new-chat-75fdb.appspot.com',
    measurementId: 'G-2022E1E408',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBusfBbyl0QRiHhf3Eqlb8yuKOkwKOp4Ns',
    appId: '1:590391716016:android:ff3071e0fc3fac0b51f375',
    messagingSenderId: '590391716016',
    projectId: 'new-chat-75fdb',
    storageBucket: 'new-chat-75fdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0BEkq0ozBZev_4ng6I1V8XA5KI2pHh14',
    appId: '1:590391716016:ios:8272c7043c818f1f51f375',
    messagingSenderId: '590391716016',
    projectId: 'new-chat-75fdb',
    storageBucket: 'new-chat-75fdb.appspot.com',
    iosClientId: '590391716016-p55caejsis87tecjo8q2tjd1obeoitl2.apps.googleusercontent.com',
    iosBundleId: 'com.oalshokri.chatAppClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0BEkq0ozBZev_4ng6I1V8XA5KI2pHh14',
    appId: '1:590391716016:ios:8272c7043c818f1f51f375',
    messagingSenderId: '590391716016',
    projectId: 'new-chat-75fdb',
    storageBucket: 'new-chat-75fdb.appspot.com',
    iosClientId: '590391716016-p55caejsis87tecjo8q2tjd1obeoitl2.apps.googleusercontent.com',
    iosBundleId: 'com.oalshokri.chatAppClass',
  );
}
